
#            - MEMCACHED_HOST=172.19.0.1
#export =http://localhost
export MEMCACHED_PORT=11211 
export ASYNC_SIGNATURE=true
export URL_ENCODED=true
export KEY_PASS=selfsignedpass
export STORE_PASS=keystorepass
export SIGNING_SECRET=selfsigned
export JWT_CERT_ALIAS=selfsigned
export HTTPSIG_CERT_ALIAS=1
export ESMO_SERVICE_DESCRIPTION=UAegean Identity Provider
export ESMO_DEFAULT_NAME=UAegean Attribute Provider
export ESMO_SUPPORTED_SIG_ALGORITHMS=RSA-SHA256
export ESMO_SUPPORTED_ENC_ALGORITHMS=RSA-SHA256
export SESSION_MANAGER_URL=https://0900b3a5.ngrok.io 
export EXPIRES=30000
export KEYSTORE_PATH=resources/testKeys/keystore.jks
export CONFIGURATION_MANAGER_URL=https://0900b3a5.ngrok.io
export ACM_NAME=ACMms001
export ACM_URL=https://esmo-gateway.es:8073
export AP_MS_NAME=APms001
export REDIRECT_JWT_SENDER=APms001
export REDIRECT_JWT_RECEIVER=ACMms001
export SUPPORTED_CLAIMS=eduPersonAffiliation,primaryAffiliation,schacHomeOrganization,mail,schacExpiryDate,mobile,eduPersonPrincipalName,eduPersonPrincipalNamePrior,displayName,sn,givenName,eduOrgLegalName,cn,eduOrgPostalAddress,eduOrgHomePageURI
export MINEDU_TOKEN_USERNAME=uaegean
export MINEDU_TOKEN_PASSWORD= 
export MINEDU_TOKEN_GRANTTYPE=password
export MINEDU_QUERYID_URL=https://gateway.interoperability.es/academicId/1.0.1/queryID
export MINEDU_QUERY_BY_AMKA=https://gateway.interoperability.es/academicId/1.0.1/student
export MINEDU_TOKEN_URL=https://validation.interoperability.es:9443/OAUTH2Proxy_1.0.0/services/oauthproxy/authorization/token
export UNIVERSITIES_CONFIG_PATH=/resources/university_codes.json
export APP_BASE_URL=https://0900b3a5.ngrok.io
export TESTING=true

